version: '3.8'

services:
  game:
    build: .
    container_name: rpg-game-dev
    volumes:
      # 掛載源碼目錄（開發時實時更新）
      - ./src:/app/src
      - ./assets:/app/assets
      - ./main.js:/app/main.js
      - ./index.html:/app/index.html
      - ./game.js:/app/game.js
      # 持久化 node_modules（避免每次重建）
      - node_modules:/app/node_modules
    environment:
      # Electron 在 Docker 中運行需要這些環境變數
      - DISPLAY=${DISPLAY}
      - ELECTRON_DISABLE_SANDBOX=1
    network_mode: host
    # X11 socket（讓 Electron 可以顯示 GUI）
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    command: npm start

  # 測試服務（獨立運行測試）
  test:
    build: .
    container_name: rpg-game-test
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - node_modules:/app/node_modules
    command: npm test

volumes:
  node_modules:
